title: Ashutosh Jha

# The `>` after `description:` means to ignore line-breaks until next key.
# If you want to omit the line-break after the end of text, use `>-` instead.
description: > 
  This website documents the academic and professional endeavours of Mr Ashutosh Jha. 

# Build settings

theme: minima

plugins:
  - jekyll-feed
  - jekyll-seo-tag

# Theme-specific settings

header_pages:
  - index.md   # Home page
  - about.md   # About page
  - portfolio.md   # Portfolio page
  - contact.md   # Contact page

defaults:
  - scope:
      path: ""  # empty string indicates all files
      type: "pages"
    values:
      layout: "home"  # Set default layout for pages to "home"

minima:
  skin: classic
